version: "3.8"
services:
  minecraft:
    image: itzg/minecraft-server:2024.2.2-java17-jdk
    environment:
      EULA: "TRUE"
      PACKWIZ_URL: "http://localhost:6942/pack.toml"
      ENABLE_AUTOPAUSE: "TRUE"
      MAX_MEMORY: "6G"
      TYPE: "QUILT"
      VERSION: "1.19.2"
      QUILT_LOADER_VERSION: "0.23.1"
    volumes:
      - ./data:/data
    depends_on:
      - packwiz
    network_mode: "host"
  packwiz:
    image: httpd:2.4.58-alpine3.19
    ports:
      - "6942:80"
    volumes:
      - ./modpack:/usr/local/apache2/htdocs/
