name = "simple_create"
author = "Mentoska44"
version = "0.1.1"
pack-format = "packwiz-modded:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c6c924cd7fc9d6e5691c94683997b33a393582f974f726781a7dbfeeba47ce6f"

[versions]
minecraft = "1.19.2"
quilt = "0.21.2"
