name = "simple_create"
author = "Mentoska44"
version = "0.1.1"
pack-format = "packwiz-modded:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "137e164abacbe28731ce603a21f4cdf653f2939305da96e9b11d01b5461eff4f"

[versions]
minecraft = "1.19.2"
quilt = "0.21.2"
