name = "simple_create"
author = "Mentoska44"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ff8589d6c8b7a1c10190d3b0578bc1f0b26b7e75780149dab2e2f3f3b75c7ba0"

[versions]
minecraft = "1.19.2"
quilt = "0.20.2"
