name = "simple_create"
author = "Mentoska44"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "61511334f1a41940c19ee25398b56ae3dd82f903e48465a2eea984464689b889"

[versions]
minecraft = "1.19.2"
quilt = "0.21.0"
