name = "simple_create"
author = "Mentoska44"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "138c4e5684d229740dceadf47a83596db8e6e56cbe56d3c0f474f37a502bc0b4"

[versions]
minecraft = "1.19.2"
quilt = "0.21.0"
