name = "Simple Create"
author = "MentoskaPraha"
version = "0.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "153ebee4a1818cc867be3a30eb46dc5b471302bff63df0e8e293346097b0347b"

[versions]
minecraft = "1.20.1"
quilt = "0.25.0"
