name = "Simple Create"
author = "Mentoska44"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7c0c20d4bbb675716cb37484c144275d70d74b3268097bf0090ba32c9dae6fe3"

[versions]
minecraft = "1.19.2"
quilt = "0.20.2"
