name = "simple_create"
author = "Mentoska44"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8679887f0a41b0296d55469308424bf28f9ff10602d117262d266e4c1fcb1e6e"

[versions]
minecraft = "1.19.2"
quilt = "0.20.2"
