name = "Simple Create"
author = "MentoskaPraha"
version = "0.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0ff17709b68d7696f30ab0131879507c6529762ec3d2003bd42ebf86a8de66ed"

[versions]
minecraft = "1.20.1"
quilt = "0.26.0-beta.1"
