name = "Simple Create"
author = "MentoskaPraha"
version = "0.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "10acb65b2cd645112d71f6122195d2e399c684c0271413951ba9a1a24e0c3949"

[versions]
minecraft = "1.19.2"
quilt = "0.23.1"
