name = "Simple Create"
author = "MentoskaPraha"
version = "0.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d2e5c4845f9b9b48123ea6c4a02eabf205784285e61f4f22c43ef7bbe88e3a4e"

[versions]
minecraft = "1.19.2"
quilt = "0.23.1"
