name = "Simple Create"
author = "MentoskaPraha"
version = "0.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4f8ee13e4e371d09e7da00e8e7476dea5639b70c43a17a574742518682d6b82a"

[versions]
minecraft = "1.19.2"
quilt = "0.23.1"
