name = "Simple Create"
author = "MentoskaPraha"
version = "0.5.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "46219eea18750a0beec03de983b75be32814b8e080e726ab2da39aaad67a56f9"

[versions]
minecraft = "1.20.1"
quilt = "0.26.0-beta.2"
