name = "Simple Create"
author = "MentoskaPraha"
version = "0.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7146393fddf72bdf5ba7a7261d2c34da69deaa4f12611a57c839cab09435a689"

[versions]
minecraft = "1.19.2"
quilt = "0.24.0"
