name = "Simple Create"
author = "MentoskaPraha"
version = "0.5.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0bfbca82ec57f6d55ae19011a2f5a0a5f8583b1dd68048d3aaaf4713c4786f06"

[versions]
minecraft = "1.20.1"
quilt = "0.26.0-beta.2"
