name = "Simple Create"
author = "MentoskaPraha"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ba9e8b535bf99b1cbe633edd765a9ee9709a23eaaf6d51b8207ff226b7e459f2"

[versions]
minecraft = "1.19.2"
quilt = "0.23.1"
