name = "Simple Create"
author = "MentoskaPraha"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4098f75810bbb504a53a32c6f6331658c26642f7562b0dc617baac518bbbd7b6"

[versions]
minecraft = "1.19.2"
quilt = "0.23.1"
