name = "Simple Create"
author = "MentoskaPraha"
version = "0.3.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "081cb33b4d1f0f6b17071d36168b5cf3b4abcd74b8405142c9c366279581a87a"

[versions]
minecraft = "1.19.2"
quilt = "0.24.0"
