name = "Simple Create"
author = "MentoskaPraha"
version = "0.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a8967c082d69d0deac1450f96ac8bba2ca1eefbc3d2446d6922a02f9ae1e7150"

[versions]
minecraft = "1.19.2"
quilt = "0.23.1"
